### PR TITLE
Rename Twingly::AMQP::Ping to Pinger

### LINKED ISSUE #33: Rename Twingly::AMQP::Ping to Pinger
A "ping" is one message. The class should be called something else. We call it `Pinger` in all other projects.

### PR DESCRIPTION
**Pull request by roback**
close #33

### CODE REVIEW

**Comment by roback** [comment]
After this gets merged I'll release a new gem version so I can start using `twingly-amqp` in klondike and norrstrom.

**Comment by walro** [comment]
> After this gets merged I'll release a new gem version so I can start using twingly-amqp in klondike and norrstrom.

Can you update all of the gems in those projects? :)

**Comment by dentarg** [comment]
I can help update projects

**Comment by roback** [comment]
> Can you update all of the gems in those projects?

Yes, Ill do that :)

**Pull request merged**
