### PR TITLE
Add RuboCop

### PR DESCRIPTION
**Pull request by walro**
I find RuboCop helpful. Not part of any automatic test yet as offences need to be fixed first.

### CODE REVIEW

**Comment by walro** [comment]
Still 18 to go, but I am happy for now. I mainly wanted RuboCop so I could check newly added source files. If anyone else wants a therapeutic session, go ahead. 😄

**Comment by walro** [comment]
> Still 18 to go, but I am happy for now. I mainly wanted RuboCop so I could check newly added source files. If anyone else wants a therapeutic session, go ahead. 😄

Fixed a few more, there are still 14 offences, not sure what we want to do in those cases hence left unaddressed. However, I don't think we need to address them now, as mentioned before, I mainly wanted RuboCop so I could, optionally, check specific files with, for example: `bundle exec rubocop lib/twingly/amqp/queue_publisher.rb`. We can create follow-up issue concerning fixing (or ignoring) the last few ones.

**Comment by walro** [comment]
@roback care to take a look? 😄

**Comment by roback** [comment]
Im on it 🚓

**Pull request merged**
