### PR TITLE
Set expiration per ping

### PR DESCRIPTION
**Pull request by roback**
RabbitMQ cannot change queue-length and queue-message-ttl, the queue has to be deleted and then redeclared.
We wanted to be able to change this value easily, so we had to use per-message-ttl instead.

This is needed for the queue between norrstrom and klondike.

see https://trello.com/c/Setqn4Fd

### CODE REVIEW

**Comment by jage** [comment]
LGTM!

**Comment by dentarg** [comment]
Instead of having "ms" in comments, couldn't it be part of the attribute name? `ping_expiration_in_ms`?

**Comment by walro** [comment]
> Instead of having "ms" in comments, couldn't it be part of the attribute name? ping_expiration_in_ms?

That will become a breaking change now. :D

**Comment by roback** [comment]
> Instead of having "ms" in comments, couldn't it be part of the attribute name? ping_expiration_in_ms?

Yes, that would have worked, but its too late now :P

**Comment by dentarg** [comment]
It's never too late.

**Pull request merged**
