### PR TITLE
Spec improvements

### LINKED ISSUE #90: Specs fail when random order is set
When I added `config.order = :random` to the spec helper, Travis failed in `pr` with seed `25967` and `push` with seed `29724`.

Seems like the specs rely on each other in some way...

### PR DESCRIPTION
**Pull request by Pontus4**
Spotted the problem with the previous configuration, which was caused by the specs using the same amqp connection.
Also sneaked in another little spec fix 😇 

Close #90

### CODE REVIEW

**Comment by walro** [comment]
> 76bdbbf

As mentioned IRL, I think this could be split into two commits. One for fixing the hosts and one for enabling random order.

PR title can be generalized to "Spec improvements" or something like that

**Review by walro — APPROVED** [review]
LGTM!

**Comment by walro** [comment]
I also noted that JRuby runs fine with the changes here, at least for the last two runs.

**Comment by Pontus4** [comment]
> I also noted that JRuby runs fine with the changes here, at least for the last two runs.

That's great! 😃

**Pull request merged**
