### PR TITLE
Optionally set source ip per ping

### LINKED ISSUE #6: Set source ip per ping
Ganges and bagmati uses the request ip as source ip which means you have to be able to set it for each ping.

### PR DESCRIPTION
**Pull request by roback**
Required by bagmati and ganges.

close #6

### CODE REVIEW

**Comment by jage** [comment]
Code looks great. I'm a bit concerned about the ability to ping multiple URLs but only set one `source_ip` though. Maybe it's not a problem ... but an alternative would be to stop supporting multiple URLs in ping.

**Comment by roback** [comment]
> Code looks great. I'm a bit concerned about the ability to ping multiple URLs but only set one source_ip though. Maybe it's not a problem ... but an alternative would be to stop supporting multiple URLs in ping.

I don't think thats a problem. If you want to ping multiple urls from the same source ip i think thats fine.

The readme needs an update though :)

**Comment by roback** [comment]
Test-run:

```ruby
> pinger = Twingly::AMQP::Ping.new(provider_name: "test", queue_name: "provider-ping", priority: 5)
> pinger.ping("http://www.example.com")
ArgumentError: :source_ip not specified
	from /Users/mattias/twingly-amqp/lib/twingly/amqp/ping.rb:47:in `message'
    ...
> pinger.ping("http://example.com", source_ip: "127.0.0.1")
```

**Comment by jage** [comment]
:+1:

**Pull request merged**
